name: Run Code Tests

on:
  push:
    paths:
      - "main/**"
  pull_request:
    paths:
      - "testcases/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure previous commit is available

      - name: Detect Changed Files
        id: changed-files
        run: |
          BEFORE_COMMIT="${{ github.event.before }}"
          if [ -z "$BEFORE_COMMIT" ] || ! git cat-file -e "$BEFORE_COMMIT"^{commit}; then
            BEFORE_COMMIT=$(git rev-parse HEAD~1)  # Use last commit as fallback
          fi
          
          CHANGED_FILES=$(git diff --name-only "$BEFORE_COMMIT" HEAD)
          if [ -z "$CHANGED_FILES" ]; then
            exit 1
          fi
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Determine File Type
        id: determine-file
        run: |
          if echo "$CHANGED_FILES" | grep -qE '\.c$'; then
            echo "language=C" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -qE '\.cpp$'; then
            echo "language=C++" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -qE '\.py$'; then
            echo "language=Python" >> $GITHUB_ENV
          elif echo "$CHANGED_FILES" | grep -qE '\.java$'; then
            echo "language=Java" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: Compile and Run C Program
        if: steps.determine-file.outputs.language == 'C'
        run: |
          cc main/main.c -o solution_c
          ./solution_c < testcases/main.c

      - name: Compile and Run C++ Program
        if: steps.determine-file.outputs.language == 'C++'
        run: |
          g++ main/main.cpp -o solution_cpp
          ./solution_cpp < testcases/main.cpp

      - name: Run Python Program
        if: steps.determine-file.outputs.language == 'Python'
        run: |
          if [ ! -f main/main.py ]; then
            exit 1
          fi
          python3 main/main.py < testcases/main.py

      - name: Compile and Run Java Program
        if: steps.determine-file.outputs.language == 'Java'
        run: |
          javac main/Main.java
          java main/Main < testcases/MainTest.java
